const projects = [
  {year:2025,month:"September",category:"Personal Care",brand:"Astroglide",theme:"Personal Lubricants Landscape",tools:"Search behavior, Mentions, Reviews",summary:"Category landscape: consumer motivations, competitive dynamics, and white space in personal lubricants.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQBx8GDEdTAXSbHXjnwBMXn4AXFL8us_yQA4mmjX1vj7IMo?e=KtN7A3"},
  {year:2025,month:"December",category:"Personal Care",brand:"Astroglide",theme:"Feel Attributes Psychological Map",tools:"Quantitative research",summary:"Psychological mapping of feel attributes: sensory expectations and emotional associations.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQCO_gvOU2RLQ5XpHt1vo_hVATc7xqzDZNZsCsfaL8Z3q6U?e=2TQm23"},
  {year:2026,month:"January",category:"Personal Care",brand:"Astroglide",theme:"Intimate Health Brand Architecture",tools:"Search behavior",summary:"Proposed brand architecture for the broader Intimate Health portfolio positioning.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQBy7L2Ydo_3RZFExzGt6X_cAYFkEwXiQ0qntcNLUZ3wz30?e=kxorSH"},
  {year:2026,month:"February",category:"Personal Care",brand:"Astroglide",theme:"Architecture & Packaging Redesign",tools:"Search behavior, Reviews",summary:"Brand architecture and packaging redesign informed by consumer research and JTBD findings.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQCY2hCQwI2IQpH7gf-fgapvAXik-kg_K1bCMoRGuv5-L4M?e=9nvJIy"},
  {year:2026,month:"March",category:"Personal Care",brand:"Astroglide",theme:"Naming Proposal for New Variants",tools:"Search behavior, Mentions",summary:"Product naming strategy based on consumer language and category codes.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQDfDzNPuEMLTrLvwBJdnb2DAf8Sr8BYFEfeEVDQT1F1DH0?e=G9oY1P"},
  {year:2026,month:"March",category:"Personal Care",brand:"Astroglide",theme:"Amplify Pleasure Positioning",tools:"Mentions, Search behavior",summary:"Strategic positioning around the Amplify Pleasure territory.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQDEDyZqigftS4GLD0cZgYu1AfsDfE7CRukv2Gh3SSXYpTk?e=G9SpYU"},
  {year:2025,month:"December",category:"Hair Care",brand:"Just For Men",theme:"Alpecin Competitor Analysis USA",tools:"Search behavior, Mentions, Reviews",summary:"Competitive landscape: Alpecin vs JFM in the US gray hair treatment market.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQBuy1md1koeSqb9QInAIG0xAQgtYGjL0zOcLUjz7vWW5Ng?e=5w9HfG"},
  {year:2025,month:"November",category:"Hair Care",brand:"Just For Men",theme:"Alpecin Competitor Analysis EU",tools:"Search behavior, Mentions",summary:"European market analysis: Alpecin positioning across UK, DE, IT.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQB4IohCz6OQS7o0znsstdW1Abm11oEujTYkrJeRqYnsYw8?e=HdeLw8"},
  {year:2025,month:"November",category:"Hair Care",brand:"Just For Men",theme:"Alpecin AI & SEO Analysis",tools:"Search behavior",summary:"AI and SEO visibility: JFM vs Alpecin across search and AI platforms.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQAJsE09CyIOQZW6uaz5ajFoAYywGO0A-rqxWbwbUNtNCKI?e=z3cBVm"},
  {year:2026,month:"January",category:"Hair Care",brand:"Just For Men",theme:"US Hair & Beard Care Benefit Territories",tools:"Search behavior, Mentions",summary:"Mapping benefit territories in men's hair and beard care for JFM positioning.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQDzgcGhnB9sS6R1HYRaNn4jASiatW0PpjxBlNrOxTQgVro?e=IC0khi"},
  {year:2025,month:"November",category:"Hair Care",brand:"Just For Men",theme:"Exploring New Territories",tools:"Search behavior, Mentions",summary:"Identifying growth territories beyond traditional gray coverage.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQBu3yQwu-k2RbiKsoJG8CmCAROm3qPBVOGEwkdgYPGXka8?e=V9cM5X"},
  {year:2026,month:"March",category:"Hair Care",brand:"Just For Men",theme:"Jobs to Be Done: Gray Hair",tools:"Mentions, Search behavior",summary:"JTBD mapping across three segments: Colorers, Shavers, and Embracers.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQDWnb01WzQ5TrQpLdQPuFjCAQm2A-50gzUGb4_MCiiSNsg?e=IjNtij"},
  {year:2025,month:"September",category:"Feminine Care",brand:"Vagisil",theme:"Social Intelligence Overview",tools:"Mentions, Search behavior",summary:"Brand conversations, sentiment drivers, and competitive positioning.",link:"https://maggiorecl-my.sharepoint.com/:p:/r/personal/joao_maggiore_cl/_layouts/15/Doc.aspx?sourcedoc=%7B4ED15515-EC32-4BF7-8179-8B0C433CB3F1%7D&file=SIA%20Maggiore%20x%20Combe%20Vagisil%202025.09.11.pptx&action=edit&mobileredirect=true"},
  {year:2025,month:"October",category:"Feminine Care",brand:"Vagisil",theme:"Anti-Itch US Declining Understanding",tools:"Search behavior, Reviews",summary:"Declining consumer understanding of Anti-Itch: perception gaps and repositioning.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQCvKOdQ1fdiRK_XSlH95BtCAQGVH2RSpxg9ZhtsRZfCkeg?e=oYfPH7"},
  {year:2025,month:"August",category:"Feminine Care",brand:"Vagisil",theme:"Vagisil Consumption Analysis",tools:"Reviews, Search behavior",summary:"Consumption patterns and usage occasions for the Vagisil portfolio.",link:"https://maggiorecl-my.sharepoint.com/:p:/r/personal/joao_maggiore_cl/_layouts/15/Doc.aspx?sourcedoc=%7BAAB07FC4-BF3D-4141-94BF-8FE7A706ECAC%7D&file=SIA%20Maggiore%20x%20Combe%20Vagisil%202025.10.01.pptx&action=edit&mobileredirect=true"},
  
  {year:2026,month:"April",category:"Feminine Care",brand:"Vagisil",theme:"Bacterial Vaginosis Consumer Intelligence",tools:"Mentions, Search behavior",summary:"BV consumer intelligence: behaviors, triggers, and brand perceptions.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQCsXn8Sbc1pRosZsnylVjgbAV_mdj6Hpb6SeHChUPH7VZg?e=Novv5g"},
  {year:2026,month:"May",category:"Feminine Care",brand:"Vagisil",theme:"Brand Strategy 2026: The Vagisil Way",tools:"Mentions, Search behavior, Reviews, Quantitative research",summary:"Comprehensive brand strategy: five cultural forces + six consumer JTBD.",link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQAXeioU3ahMTY5nbCd8_kRGAfBZrIeqNs0kM_-pmJEOlXg?e=aDLFz5"}
]

const iepProjects = [
  {brand:"Just For Men",experiment_id:"E01",project_name:"Gray Reverse",category:"Hair Care",rounds:2,year:2025,link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQBCPyUVOyzdSo7JExw-FV8sAUbHVVHVCHJgSN6d47KcSQ4?e=jJNqVe",summary:"Testing consumer response to a gray-reversing product concept via Meta landing pages."},
  {brand:"Just For Men",experiment_id:"E02",project_name:"Control GX Gradual",category:"Hair Care",rounds:1,year:2026,link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQCV4DtQdU0dSJRK-vgJ8rQpAaa-sePT7IaldCM-kPjvwEQ?e=VLSlet",summary:"Evaluating messaging and claims for the gradual gray reduction product line."},
  {brand:"Just For Men",experiment_id:"E03",project_name:"JFM One",category:"Hair Care",rounds:1,year:2026,link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQB7F-S77t9OSIBYnPza3f2TAUCFxcDNY8v9HdMfrnwb4gQ?e=0lTIZC",summary:"Testing the 'One' product concept: a single all-in-one solution for gray hair and beard."},
  {brand:"Vagisil",experiment_id:"E01",project_name:"Vagisil BV",category:"Feminine Care",rounds:1,year:2026,link:"https://maggiorecl-my.sharepoint.com/:p:/g/personal/joao_maggiore_cl/IQCCzUP5yXzDSZX0q_cWexNPAY9UjCogiUc8LdbLV98At4o?e=bSjYFG",summary:"Testing messaging and positioning for the Bacterial Vaginosis product line."}
]

var audits=[]

var platforms=['ChatGPT','Perplexity','Gemini','Google AI Overview','Claude']

var docLens=[]

var tiles=[]

var suggestions=['What do we know about gray hair consumer segments?','Personal lubricants category landscape','Vagisil brand perception and equity','Alpecin competitive analysis','Intimate wellness consumer barriers','What are the JTBD for personal care?']

let _askCorpus=[]